name = "ParaxialBeamPropagation"
uuid = "6a5419b6-6cb4-4458-8a6f-f8c5617a8bed"
authors = ["Marcos Gil"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
